[package]
name = "revpi-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.126"
thiserror = "1.0.31"
# serde_json = "1.0.81"
# serde = "1.0.137"
