name: Test and build for ARM
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/cargo@v1.0.1
      with:
        command: test
        args: --workspace --all-features
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable-x86_64-unknown-linux-gnu 
        target: aarch64-unknown-linux-gnu
    - uses: actions-rs/cargo@v1.0.1
      with:
        command: build
        args: --workspace --all-features --release --target=aarch64-unknown-linux-gnu
    - uses: actions/upload-artifact@v3.1.0
      with:
        name: aarch64-unknown-linux-gnu
        path: target/aarch64-unknown-linux-gnu/release/librevpi.rlib
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/cargo@v1.0.1
      with:
        command: doc
        args: --workspace --no-deps --all-features
